format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '585', y: '559', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: drv_spi_0, namespace: DRIVER LAYER, id: 'drvExtMacEnc28j60_0:ENC28J60_SPI',
      targetAttachmentID: drv_spi}
