files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx_eth_sk2
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: BBD4812BD05458C62BDD2D4D192EBA9C
  logicalPath: config\pic32mx_eth_sk2
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BBD4812BD05458C62BDD2D4D192EBA9C
- generatedChecksum: 89B2CF6741179C3D45BA8E6CACFE3B0E
  logicalPath: config\pic32mx_eth_sk2
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 89B2CF6741179C3D45BA8E6CACFE3B0E
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mx_eth_sk2.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 2F8D2F5AE2544E2AAB9FD3A1345E08B8
  logicalPath: config\pic32mx_eth_sk2\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F8D2F5AE2544E2AAB9FD3A1345E08B8
- generatedChecksum: B9075C50D6E5312528847AA1098C60AD
  logicalPath: config\pic32mx_eth_sk2\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B9075C50D6E5312528847AA1098C60AD
- generatedChecksum: A397346963B2959657EF85FD415D1628
  logicalPath: config\pic32mx_eth_sk2\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A397346963B2959657EF85FD415D1628
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mx_eth_sk2\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 1E5CA1CBAC346A74EC2BFE040DC88828
  logicalPath: config\pic32mx_eth_sk2
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E5CA1CBAC346A74EC2BFE040DC88828
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx_eth_sk2
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx_eth_sk2
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_eth_sk2\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 37436424B3DFA2A4948662880FFD2E29
  logicalPath: config\pic32mx_eth_sk2\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 37436424B3DFA2A4948662880FFD2E29
- generatedChecksum: 09B7A89A19194B84EBB4FEAF0105627A
  logicalPath: config\pic32mx_eth_sk2\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 09B7A89A19194B84EBB4FEAF0105627A
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_eth_sk2
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 27954F44000DB58CD56D0372E7A00395
  logicalPath: config\pic32mx_eth_sk2
  name: p32MX795F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 27954F44000DB58CD56D0372E7A00395
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_eth_sk2;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_eth_sk2;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
