format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIcmp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_ICMP_ECHO_BROADCASTS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '560', y: '20', id: tcpipIcmp}
